version: '3'
services:
  strapi:
    image: rcdelacruz/my-strapi-app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: cbEBsGziVvhsG19NgUMS8Q==,cldVfLJCaic8YKBdPGlrrg==,bLK+E0g1OqXXZRehfruvmg==,BrDwbmyfZDIqNYNq4gjT8A==
      API_TOKEN_SALT: JlnrvFNv6SoGVve8G1OiYg==
      ADMIN_JWT_SECRET: Churc975EvecMwbrF1V0yQ==
      TRANSFER_TOKEN_SALT: HrV+i4amf6B//dMPXFFiKA==
    ports:
      - "1338:1337"
    volumes:
      - ./app:/usr/src/api/strapi-app
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
